### ISSUE TITLE
Colorless .support syntax

### ISSUE THREAD

**Issue by nicktimko** [burntime/atom-monokai#10]
I'm not sure where it comes from in the fairly small `syntax-variables.less` file, but when I'm looking at Python source using MagicPython (the not-broken [maybe-soon-to-replace atom/language-python](https://github.com/atom/language-python/issues/109) highlighter), all the built-in names that are colored by Atom Dark using the `support` class aren't. Not sure if it's some funky interaction between the two packages, but had to pick somewhere to complain :D

![screen shot 2016-04-25 at 5 43 43 pm](https://cloud.githubusercontent.com/assets/5297556/14801256/875d1f38-0b0d-11e6-87b4-6a5f9c15878e.png)
![screen shot 2016-04-25 at 5 44 05 pm](https://cloud.githubusercontent.com/assets/5297556/14801257/875eae48-0b0d-11e6-8f29-4cfcbe072820.png)

**Comment by burntime** [comment]
@nicktimko please update and try again.
