### ISSUE TITLE
Deprecated selector in `atom-monokai/index.less`

### ISSUE THREAD

**Issue by adimol** [burntime/atom-monokai#12]
In `atom-monokai/index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `.atom-text-editor,
:host` => `.atom-text-editor,atom-text-editor`

* `.atom-text-editor .invisible-character,
:host .invisible-character,
.atom-text-editor .indent-guide,
:host .indent-guide` => `.atom-text-editor .invisible-character,atom-text-editor .invisible-character,
.atom-text-editor .indent-guide,atom-text-editor .indent-guide`

* `.atom-text-editor .gutter,
:host .gutter` => `.atom-text-editor .gutter,atom-text-editor .gutter`

* `.atom-text-editor .gutter .line-number,
:host .gutter .line-number` => `.atom-text-editor .gutter .line-number,atom-text-editor .gutter .line-number`

* `.atom-text-editor .gutter .line-number.folded,
:host .gutter .line-number.folded,
.atom-text-editor .gutter .line-number:after,
:host .gutter .line-number:after,
.atom-text-editor .fold-marker:after,
:host .fold-marker:after` => `.atom-text-editor .gutter .line-number.folded,atom-text-editor .gutter .line-number.folded,
.atom-text-editor .gutter .line-number:after,atom-text-editor .gutter .line-number:after,
.atom-text-editor .fold-marker:after,atom-text-editor .fold-marker:after`

* `.atom-text-editor .selection .region,
:host .selection .region` => `.atom-text-editor .selection .region,atom-text-editor .selection .region`

* `.atom-text-editor .highlights .current-result .region,
:host .highlights .current-result .region` => `.atom-text-editor .highlights .current-result .region,atom-text-editor .highlights .current-result .region`

* `.atom-text-editor .highlights .find-result .region,
:host .highlights .find-result .region` => `.atom-text-editor .highlights .find-result .region,atom-text-editor .highlights .find-result .region`

* `.atom-text-editor .line-number.cursor-line-no-selection,
:host .line-number.cursor-line-no-selection` => `.atom-text-editor .line-number.cursor-line-no-selection,atom-text-editor .line-number.cursor-line-no-selection`

* `.comment` => `.syntax--comment`

* `.entity` => `.syntax--entity`

* `.keyword` => `.syntax--keyword`

* `.storage` => `.syntax--storage`

* `.storage.type,
.support.type.stdint,
.support.type.sys-types` => `.syntax--storage.syntax--type,
.syntax--support.syntax--type.syntax--stdint,
.syntax--support.syntax--type.syntax--sys-types`

* `.support.function.any-method,
.support.function.C99` => `.syntax--support.syntax--function.syntax--any-method,
.syntax--support.syntax--function.syntax--C99`

* `.support.type.exception` => `.syntax--support.syntax--type.syntax--exception`

* `.constant` => `.syntax--constant`

* `.constant.numeric,
.constant.boolean` => `.syntax--constant.syntax--numeric,
.syntax--constant.syntax--boolean`

* `.variable` => `.syntax--variable`

* `.delimiter,
.brace` => `.syntax--delimiter,
.syntax--brace`

* `.invalid.deprecated` => `.syntax--invalid.syntax--deprecated`

* `.invalid.illegal` => `.syntax--invalid.syntax--illegal`

* `.string` => `.syntax--string`

* `.string .constant.character.escape` => `.syntax--string .syntax--constant.syntax--character.syntax--escape`

* `.string.regexp` => `.syntax--string.syntax--regexp`

* `.string.regexp .source.ruby.embedded,
.string.regexp .string.regexp.arbitrary-repitition` => `.syntax--string.syntax--regexp .syntax--source.syntax--ruby.syntax--embedded,
.syntax--string.syntax--regexp .syntax--string.syntax--regexp.syntax--arbitrary-repitition`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by arsari** [comment]
When released 0.10.5 will be publish.  Atom v1.13.0 show this packaged as not compatible.

**Comment by 2114L3** [comment]
also have this issue.
archlinux 4.8.13-1-ARCH
atom 1.13.0 x64

if this fix was completed it has not resolved the reported error

**Comment by burntime** [comment]
@2114L3 Should be fixed not, I missed out something, the deprecation warning should be gone now?

**Comment by arsari** [comment]
great!!! now is working find. no deprecation for now...

**Comment by 2114L3** [comment]
brilliant! 0.10.7 has solved it here. thanks
