### ISSUE TITLE
One Dark UI Editor White Scrollbars

### ISSUE THREAD

**Issue by gungorbudak** [burntime/atom-monokai#7]
Hi,

I'm using Atom 1.0.19 in my Linux Mint 17.3 One Dark UI Theme configured. I installed Atom Monokai syntax theme but it looks like the scrollbars for One Dark UI aren't correctly styled. Horizontal and vertical scrollbars appear white as if One Light UI Theme was configured.

This is how it looks: [Screenshot](http://i.imgur.com/pudm0Yv.png)

What could be the issue?

Thanks!

**Comment by burntime** [comment]
Hi, 

Is the bug still there after restarting Atom? Had a similar issues sometimes after switching between themes. Usually they disappear after restart. 

I can not reproduce the problem on my Mac, will try later on Ubuntu.

**Comment by burntime** [comment]
Okay its reproducible on Ubuntu. I'll have a look.

**Comment by burntime** [comment]
Here is a quickfix for the "Your Stylesheet" CSS:

```
atom-text-editor /deep/ ::-webkit-scrollbar {
  &-track { background-color: initial !important;}
  &-corner { background-color: initial !important;}
  &-thumb {
    background-color: @text-color !important;
    border-color: transparent !important;
  }
 }
```

I'll fix this in the next release.

**Comment by gungorbudak** [comment]
Thanks! I tried but it didnt't work with `background-color`. It only works with `background`.

```
atom-text-editor /deep/ ::-webkit-scrollbar {
  &-track { background: initial !important;}
  &-corner { background: initial !important;}
  &-thumb {
    background: @text-color !important;
    border: transparent !important;
  }
}
```

Is this Less by the way? I realized wrap guide is also white. I'm not sure if that's intended though but it looks weird in white in my opinion. I don't know but it looks okay with `background-color: #444;`.

```
atom-text-editor::shadow .wrap-guide {
  background-color: #444;
}
```

**Comment by burntime** [comment]
Should be fixed now
